{{ if .Values.airflow.secrets.create_secrets_file }}
apiVersion: v1
kind: Secret
metadata:
  name: {{required "An airflow secrets filename is required" .Values.airflow.secrets.secret_file}}
  namespace: {{ .Release.Namespace}}
  annotations:
    force_redeploy: {{ randAscii 10 | quote }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.airflow.db.password | b64enc }}
  DB_HOST: {{ .Values.airflow.db.host | b64enc}}
{{- range $key, $value := .Values.airflow.secrets.extra_secrets}}
  {{ $key }}: {{ $value | b64enc}}
{{- end}}
{{ end }}