{{ if .Values.airflow.remoteLogging.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "A logging secret file is required" .Values.airflow.remoteLogging.secretName}}
  namespace: {{ .Release.Namespace}}
  annotations:
    force_redeploy: {{ randAscii 10 | quote }}
type: Opaque
data:
  {{- if .Values.airflow.remoteLogging.enable}}
  REMOTE_LOGGING_SECRET: {{required "A remote logging secret is required to access you logging store if the chart is to create a secret file." .Values.airflow.remoteLogging.secretName | b64enc }}
  {{- end }}
{{ end}}