apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace}}
  name: {{  .Release.Name }}-scheduler
  labels:
    app: "airflow-cluster"
    component: scheduler
spec:
  selector:
    matchLabels:
      app: "airflow-cluster"
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "airflow-cluster"
        component: scheduler
      annotations:
        # Forces a redeploy on any upgrade.
        force_redeploy: {{ randAscii 10 | quote }}
    spec:
      serviceAccountName: "airflow"
      containers:
        - name: scheduler
          image: "{{ required "airflow image is required" .Values.airflow.image.repository }}:{{ required "airflow image is required" .Values.airflow.image.tag | toString }}"
          command:
            - sh
            - /entrypoint.sh
            - scheduler
          envFrom:
            - configMapRef:
                name: "airflow-config"
            - configMapRef:
                name: "worker-config"
            - configMapRef:
                name: "logging-config"
            - secretRef:
                name: {{ required "Logging Secret required" .Values.airflow.remoteLogging.secretName}}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{required "a secrets file is required" .Values.airflow.secrets.secretName}}
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.airflow.secrets.secretName}}
                  key: DB_HOST
            {{- if .Values.airflow.remoteLogging.enable }}
            - name: "AIRFLOW_CONN_{{ .Values.airflow.remoteLogging.connName | upper}}"
              value: "{{ .Values.airflow.remoteLogging.connType | lower}}://$(REMOTE_LOGGING_SECRET)@{{ .Values.airflow.remoteLogging.path }}"
            - name: AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW_CONN_{{ .Values.airflow.remoteLogging.connName | upper}}
              value: "{{ .Values.airflow.remoteLogging.connType | lower}}://$(REMOTE_LOGGING_SECRET)@{{ .Values.airflow.remoteLogging.path}}"
            {{- end }}
            {{- if .Values.airflow.envVars -}}
            {{- range $key, $value := .Values.airflow.envVars }}
            - name: {{ $key }}
              value: {{ quote $value }}
            {{- end }}
            {{- end }}
            {{-  range $secret_name, $secret_value := .Values.airflow.secrets.extraSecrets}}
            - name: {{ $secret_name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.airflow.secrets.secretName}}
                  key: {{ $secret_name }}
          {{-  end }}
          resources:
            requests:
              cpu: {{ .Values.airflow.scheduler.requests.cpu}}
              memory: {{ .Values.airflow.scheduler.requests.memory}}

