apiVersion: v1
kind: ServiceAccount
metadata:
  name: "airflow"
  namespace: {{.Release.Namespace}}
  labels:
    app: "airflow"
    tier: "rbac"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "airflowrole"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "airflow"
    tier: "rbac"
rules:
  - apiGroups: [""]
    resources:
      - "pods"
    verbs: ["create", "get", "delete", "list", "watch"]
  - apiGroups: [""]
    resources:
      - "pods/log"
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources:
      - "pods/exec"
    verbs: ["create", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-binding
  namespace: {{.Release.Namespace}}
  labels:
    app: "airflow"
    tier: "rbac"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "airflowrole"
subjects:
  - kind: ServiceAccount
    name: "airflow"
