{{ if .Values.airflow.webserver.ingress.enable}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name}}-ui-external-ingress"
  namespace: {{ .Release.Namespace }}
{{- with .Values.airflow.webserver.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ .Release.Name}}
spec:
  rules:
    - host: {{ .Values.airflow.webserver.ingress.host }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: "{{ .Release.Name }}-ui-service"
              servicePort: http
{{ end}}